### ISSUE TITLE
How to check Card Type that swaped

### ISSUE THREAD

**Issue by Tusshark** [sgbj/Dukpt.NET#15]
hi
    Actually , in my side encryption and decryption of card details or track1 and track2 details is correct.
but after decryption process i am unable to find out which card is swiped . So please give me the resolution for that how i am verify card type from decrypted track1 or track2 details.

**Comment by sgbj** [comment]
Track 2 contains the credit card number, and a standard way of determining the card type is based on the first 6 digits of the card number. See [this answer](https://stackoverflow.com/questions/72768/how-do-you-detect-credit-card-type-based-on-number) on StackOverflow.
