### ISSUE TITLE
How to get complete card number from Track details

### ISSUE THREAD

**Issue by Tusshark** [sgbj/Dukpt.NET#16]
Actually, I want to get complete card number. when we swiped card with magtek device . is it possible to get it. so please tell me the whole procedure for that.

**Comment by sgbj** [comment]
The credit card number exists in track 2. [This Wikipedia article](https://en.m.wikipedia.org/wiki/ISO/IEC_7813) describes the format of the track data with examples. The card number would be the PAN part of the track data.
