### ISSUE TITLE
How to Get CVV number from decrypted data on  secureMag Reader

### ISSUE THREAD

**Issue by SaddamBInSyed** [sgbj/Dukpt.NET#9]
Hi ..

I have successfully done the decrypt and encrypt operation. now i need the CVV number for to disply into the GUI.

How can i get the CVV number for IDTech SecureMag Reader..

Kindly help me

**Comment by ichoes** [comment]
CVV is not part of the track data.
https://en.wikipedia.org/wiki/Magnetic_stripe_card
